### ISSUE TITLE
TypeError: can't pickle async_generator objects

### ISSUE THREAD

**Issue by darland** [pnuckowski/aioresponses#149]
My tests started fall down after I pull the new version

```
Traceback (most recent call last):
  File "/Users/project/app/views.py", line 659, in _post
    responses = await asyncio.gather(*tasks)
  File "/Users/project/utils/ncapi/client.py", line 314, in upload_verification_document
    return await self._action("uploadVerificationDocument", "post", data, files=True, single_file=True)
  File "/Users/project/utils/ncapi/client.py", line 181, in _action
    res = await request(self.url(action_name), data=result)
  File "/Users/env-2fy-KEPT/lib/python3.7/site-packages/aioresponses/core.py", line 338, in _request_mock
    self.requests[key].append(RequestCall(args, copy.deepcopy(kwargs)))
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/Users/env-2fy-KEPT/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle async_generator objects
Traceback (most recent call last):
  File "/Users/project/app/views.py", line 659, in _post
    responses = await asyncio.gather(*tasks)
TypeError: can't pickle async_generator objects
```

**Comment by rpliva** [comment]
Similar error after update to `0.6.2`

**Comment by rpliva** [comment]
Here is a simple example of my case, where both tests are green when I use `aioresponses = 0.6.1` but when I use `aioresponses = 0.6.2` test `test_error` failed because of error above

```
import aiofiles
import aiohttp
import pytest
from aioresponses import aioresponses


async def _file_sender(file_name: str):
    async with aiofiles.open(file_name, "rb") as f:
        chunk = await f.read(64 * 1024)
        while chunk:
            yield chunk
            chunk = await f.read(64 * 1024)


async def send_file():
    async with aiohttp.ClientSession() as session:
        async with session.post(
            "http://example.com", data=_file_sender("test.py")
        ) as response:
            return await response.json()


async def send_text():
    async with aiohttp.ClientSession() as session:
        async with session.post("http://example.com", data="test") as response:
            return await response.json()


@pytest.mark.asyncio
async def test_ok():
    with aioresponses() as m:
        m.post("http://example.com", payload={"success": "ok"}, status=200)
        r = await send_text()

        assert r["success"] == "ok"


@pytest.mark.asyncio
async def test_error():
    with aioresponses() as m:
        m.post("http://example.com", payload={"success": "ok"}, status=200)
        r = await send_file()

        assert r["success"] == "ok"

```

**Comment by mikenerone** [comment]
"Me too", 0.6.2 breaks many of our async tests in the same way.

**Comment by mikenerone** [comment]
The problem merge is #143.

**Comment by Colin-b** [comment]
Yes I saw this but unfortunately my use cases and the test cases did not cover this (non deep copyable args). I will try to see if there is a way to have a request stored as it should have been sent, a quick fix would be to check if the deepcopy would work, and if not, keep previous behaviour (with the issue that come up with).

In the meantime everyone else is of course free to come up with a PR solving the issue raised by this ticket as I am not the maintainer on this project ;-)

**Comment by mikenerone** [comment]
@Colin-b Regarding #143, does `aiohttp` itself make any attempt to preserve the request kwargs? I'm guessing no, since it doesn't exhibit this error. Assuming not, then while I understand the urge to avoid a mutable-arguments issue in general, if the library being mocked doesn't do so, isn't there little point in doing so in the mock itself? In addition to causing this issue, doesn't it also potentially mask a bug that actually exists in production?

**Comment by Colin-b** [comment]
This lib does not reproduce the exact behaviour of aiohttp, the way mongomock does with pymongo for instance. The issue does not exists in aiohttp because parameters are used to generate a query that is sent. However this library does not reproduce the request actually sent by aiohttp, instead it saves the parameters provided when querying. This is a huge difference, as the request that is saved by this library does not exactly match what is actually sent by aiohttp, so producing false positive in test cases potentially.

That was the reason for the initial fix. As I said, a clean one would be to store a request closer to what is actually sent by aiohttp, but this requires a bit more work than a simple deepcopy on every attribute.

However it would fix some other issues in current version of the lib, such as the inability to retrieve actual headers that are sent if specified at session level.

**Comment by mikenerone** [comment]
Ah, right...ok, I'm sold on the need.
