### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources' (Python 3.11)

### ISSUE THREAD

**Issue by jacebrowning** [pnuckowski/aioresponses#225]
Starting in Python 3.8, `importlib` is recommended over `pkg_resources`: https://docs.python.org/3/library/importlib.metadata.html?highlight=pkg_resources

`pkg_resources` is no longer included in some distributions of Python 3.10+ including CircleCI Python images.

**Comment by ppena-LiveData** [comment]
And from looking at [this setuptools commit](https://github.com/pypa/setuptools/commit/a1aeda391a0c462ea53627bcdf50dd4c0daadaed), `pkg_resources` has been deprecated since `setuptools` `v67.5.0`, so for those of us who run `pytest` with `filterwarnings = ["error"]`, that deprecation warning breaks the `pytest`.

**Comment by victorpaleologue** [comment]
Fixed in #241
